name: nyc_airbnb_dev
channels:
  - conda-forge
dependencies:
  - python=3.9.15
  - pip=24.3.1
  - jupyterlab=4.0.13
  - pandas=1.5.3
  - numpy=1.26.4
  - matplotlib=3.6.3
  - scikit-learn=1.1.3
  - scipy=1.10.1
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - pip:
      - mlflow==2.9.2
      - wandb==0.15.12
