name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15
  - pip
  - pandas=1.5.3
  - numpy=1.23.5
  - scikit-learn=1.1.3
  - matplotlib=3.6.3
  - jupyterlab=3.6.3
  - hydra-core=1.3.2
  - pip:
      - mlflow==2.7.1
      - wandb==0.15.12
